import { z } from 'zod';

import {
  attractionLocalizationSchema,
  attractionStatusSchema,
  bookingRequirementSchema,
  childAgeBandSchema,
  confidenceSchema,
  countryCodeSchema,
  dogPolicySchema,
  indoorOutdoorSchema,
  priceLevelSchema,
  relevanceSchema,
  seasonSchema,
  suitabilitySchema,
  strollerSuitabilitySchema,
  transportModeSchema,
  verificationStateSchema,
  visitorLanguageSchema,
  wheelchairAccessSchema,
} from '../entities/attraction.js';
import { exceptionalClosureSchema, openingScheduleSchema } from '../opening-hours/index.js';

export const editorPriceSchema = z.object({
  audience: z.enum(['ADULT', 'CHILD', 'FAMILY', 'SENIOR', 'GROUP', 'OTHER']),
  amount: z.number().finite().nonnegative(),
  currency: z.enum(['EUR', 'CHF']),
  validFrom: z.string().date().nullable(),
  validTo: z.string().date().nullable(),
  note: z.string().trim().nullable(),
  confidence: confidenceSchema,
});

export const attractionEditorPayloadSchema = z.object({
  id: z.string().uuid().nullable(),
  expectedUpdatedAt: z.string().datetime().nullable(),
  status: attractionStatusSchema,
  countryCode: countryCodeSchema,
  municipality: z.string().trim().min(1),
  regionCode: z.string().trim().min(1),
  latitude: z.number().finite().min(-90).max(90),
  longitude: z.number().finite().min(-180).max(180),
  scopeException: z.boolean(),
  scopeExceptionReason: z.string().trim().nullable(),
  editorialRelevance: relevanceSchema,
  verificationState: verificationStateSchema,
  indoorOutdoor: indoorOutdoorSchema,
  rainSuitability: suitabilitySchema.nullable(),
  heatSuitability: suitabilitySchema.nullable(),
  seasons: z.array(seasonSchema),
  typicalDurationMin: z.number().int().positive().nullable(),
  typicalDurationMax: z.number().int().positive().nullable(),
  priceLevel: priceLevelSchema.nullable(),
  bookingRequirement: bookingRequirementSchema,
  bookingUrl: z.string().url().nullable(),
  officialWebsite: z.string().url().nullable(),
  childAgeBands: z.array(childAgeBandSchema),
  foodOnSite: z.boolean().nullable(),
  cafeOnSite: z.boolean().nullable(),
  picnicAllowed: z.boolean().nullable(),
  toilets: z.boolean().nullable(),
  strollerSuitable: strollerSuitabilitySchema.nullable(),
  wheelchairAccess: wheelchairAccessSchema.nullable(),
  wheelchairToilet: z.boolean().nullable(),
  dogPolicy: dogPolicySchema.nullable(),
  visitorLanguages: z.array(visitorLanguageSchema),
  transportModes: z.array(transportModeSchema),
  nearestStopName: z.string().trim().nullable(),
  nearestStopDistanceM: z.number().int().nonnegative().nullable(),
  parkingAvailability: z.enum(['ON_SITE', 'NEARBY', 'DIFFICULT', 'NONE']).nullable(),
  parkingNote: z.string().trim().nullable(),
  bicycleAccess: z.boolean().nullable(),
  bicycleNote: z.string().trim().nullable(),
  categoryCodes: z.array(z.string().trim().min(1)),
  localizations: z.array(attractionLocalizationSchema).length(2),
  criticalFacts: z.object({
    name: verificationStateSchema,
    location: verificationStateSchema,
    hours: verificationStateSchema,
  }),
  openingSchedule: openingScheduleSchema.nullable(),
  closures: z.array(exceptionalClosureSchema),
  prices: z.array(editorPriceSchema),
});

export type AttractionEditorPayload = z.infer<typeof attractionEditorPayloadSchema>;
