import type { AttractionEditorPayload } from '@lake/domain';

export function createEmptyAttractionEditorPayload(): AttractionEditorPayload {
  return {
    id: null,
    expectedUpdatedAt: null,
    status: 'DRAFT',
    countryCode: 'DE',
    municipality: 'Konstanz',
    regionCode: 'KONSTANZ_SEERHEIN',
    latitude: 47.66,
    longitude: 9.17,
    scopeException: false,
    scopeExceptionReason: null,
    editorialRelevance: 'MEDIUM',
    verificationState: 'UNVERIFIED',
    indoorOutdoor: 'MIXED',
    rainSuitability: null,
    heatSuitability: null,
    seasons: ['ALL_YEAR'],
    typicalDurationMin: 60,
    typicalDurationMax: 120,
    priceLevel: null,
    bookingRequirement: 'NONE',
    bookingUrl: null,
    officialWebsite: null,
    childAgeBands: ['6-9'],
    foodOnSite: null,
    cafeOnSite: null,
    picnicAllowed: null,
    toilets: null,
    strollerSuitable: 'UNKNOWN',
    wheelchairAccess: 'UNKNOWN',
    wheelchairToilet: null,
    dogPolicy: 'UNKNOWN',
    visitorLanguages: ['DE', 'EN'],
    transportModes: ['WALK', 'PUBLIC_TRANSPORT'],
    nearestStopName: null,
    nearestStopDistanceM: null,
    parkingAvailability: null,
    parkingNote: null,
    bicycleAccess: null,
    bicycleNote: null,
    categoryCodes: ['MUSEUM'],
    localizations: [
      {
        locale: 'de',
        name: '',
        slug: '',
        summary: null,
        description: null,
        practicalNotes: null,
        translationState: 'SOURCE',
      },
      {
        locale: 'en',
        name: '',
        slug: '',
        summary: null,
        description: null,
        practicalNotes: null,
        translationState: 'NEEDS_REVIEW',
      },
    ],
    criticalFacts: { name: 'UNVERIFIED', location: 'UNVERIFIED', hours: 'UNVERIFIED' },
    openingSchedule: {
      validFrom: '2026-01-01',
      validTo: '2027-12-31',
      hoursUnknown: false,
      rules: [
        {
          daysOfWeek: ['MON'],
          opens: '09:00',
          closes: '17:00',
          appliesOnPublicHolidays: 'AS_WEEKDAY',
          holidayCalendarCode: 'DE-BW',
        },
      ],
    },
    closures: [],
    prices: [],
  };
}
